name: Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: List directory contents
      run: ls -R

    - name: Build Docker image
      run: docker build -t mynode .

    - name: Run Docker container
      run: docker run -p 3000:3000 -d mynode